networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  mariadb:
    driver: ${VOLUMES_DRIVER}
  assets:
    driver: ${VOLUMES_DRIVER}

secrets:
  server-certificate:
    file: ./data/certbot/certs/_.piyonakademi.com/cert.pem
  server-keyfile:
    file: ./data/certbot/certs/_.piyonakademi.com/key.pem

services:

##########################################################
### MariaDB ##############################################
##########################################################
  mariadb:
    restart: always
    hostname: localhost
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb_3306
    build:
      context: ./config/mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      - ${DATA_PATH_HOST}/database/mariadb:/var/lib/mysql
      - ${MARIADB_RESTORE_PATH}:/home/restore
      - ./scripts:/home/scripts
    profiles: [mandatory]
    ports:
      - "${MARIADB_PORT}:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptoor"]
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USERNAME}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_BACKUP_PATH=${MARIADB_BACKUP_PATH}
      - MARIADB_MAX_ALLOWED_PACKET=32M
      - MARIADB_CHARACTER_SET_SERVER=utf8
      - MARIADB_COLLATION_SERVER=utf8_general_ci
    networks:
      - backend


##########################################################
### NGINX Server #########################################
##########################################################
  nginx:
    restart: always
    container_name: ${COMPOSE_PROJECT_NAME}_nginx_${NGINX_HOST_HTTP_PORT}
    hostname: nginx.localhost
    # mounts as /run/secrets/<secret_name>
    secrets:
      - server-certificate
      - server-keyfile
    stop_grace_period: 1s
    build:
      context: ./config/nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    profiles:
      - mandatory
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
#      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - drupalX
    networks:
      - backend
#    healthcheck:
#      - disable: true
#      - test: cgi-fcgi -bind -connect kuzguni_drupalX_fpm:9999 >/dev/null 2>&1 || exit 1
    volumes:
      - assets:/home/assets:ro,z

      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/home/config
      - ./data/nginx/modules:/home/modules
#      - ./data/nginx/keys:/etc/nginx/ssl/

      - ./opt/drupal:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/www:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl


##########################################################
### phpMyAdmin ###########################################
##########################################################
  phpmyadmin:
    restart: always
    build: ./config/phpmyadmin
    container_name: ${COMPOSE_PROJECT_NAME}_phpmyadmin_${PMA_PORT}
    hostname: database
    profiles:
      - mandatory
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=kuzguni_mariadb_3306
      - MYSQL_USER=${MARIADB_USERNAME}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MAX_EXECUTION_TIME=${PMA_MAX_EXECUTION_TIME}
      - MEMORY_LIMIT=${PMA_MEMORY_LIMIT}
      - UPLOAD_LIMIT=${PMA_UPLOAD_LIMIT}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - "${PMA_DB_ENGINE}"
    networks:
      - frontend
      - backend


##########################################################
### Drupal-X #############################################
##########################################################
# https://github.com/docker-library/repo-info/blob/master/repos/drupal/local/10.4.8-fpm.md
  drupalX:
    image: arm64v8/drupal:10.4.8-fpm
    container_name: ${COMPOSE_PROJECT_NAME}_drupalX_fpm
    restart: always
    tty: true
    networks:
      - backend
    profiles:
      - mandatory
    ports:
      - 9999:9999
    depends_on:
      - "${PMA_DB_ENGINE}"
    volumes:
      - type: volume
        source: assets
        target: /opt/drupal/web
        volume:
          nocopy: false
      # override PHP settings
      - ./data/phpfpm/php/php.ini-development:/usr/local/etc/php/php.ini-development
      - ./data/phpfpm/php/php.ini-production:/usr/local/etc/php/php.ini-production
      # override PHP-FPM settings
      - ./data/phpfpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./data/phpfpm/php-fpm.d:/usr/local/etc/php-fpm.d
      # override Drupal folders
      - ./data/drupalX/modules:/var/www/html/modules
      - ./data/drupalX/sites:/var/www/html/sites
      - ./data/drupal-10/profiles:/var/www/html/profiles
      - ./data/drupal-10/themes:/var/www/html/themes
      - ./data/drupal-10/libraries:/var/www/html/libraries
