<?php
/**
 * @file
 * Players and lists for League module.
 */

function player_list_overview_types() {
  $content = l("Manage League Player entity fields", 'admin/structure/player_list/manage');
  return $content;
}

function player_list_information() {
  $content = 'Manager fields in the League Player entity';
  return $content;
}

/*******************************************************************************
 * Hook Functions (Drupal)
 ******************************************************************************/

/**
 * Implements hook_permission().
 *
 */
function player_list_permission() {
  return array(
    'rating list' => array(
      'title' => t('player list'),
      'description' => t('Administer Player list module'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function player_list_menu() {
  
  // Admin menu options

  $items['admin/structure/player_list'] = array(
    'title' => 'League Players',
    'description' => 'Manage Players',
    'page callback' => 'player_list_overview_types',
    'access arguments' => array('player list'),
  );

  $items['admin/structure/player_list/manage'] = array(
    'title' => 'Manage Player Entity',
    'description' => 'Manage Players',
    'page callback' => 'player_list_information',
    'access arguments' => array('player list'),
  );
  $items['admin/structure/player_list/manage/player_list/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // List player lists for an org
  $items['player_list/plists/%'] = array(
    'title' => 'Player Lists',
    'page callback' => 'player_lists_org',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'access arguments' => array(1,'organisation'),
    'type' => MENU_LOCAL_TASK,
    'weight' => -12,
  );

  $items['player_list/add'] = array(
    'title' => 'Add Player',
    'page callback' => 'player_list_add_to_org',
    'page arguments' => array(2),
    'access callback' => 'player_list_org_permission',
    'access arguments' => array(2),
    'file' => 'player_list_update.inc',
  );

  // Note: the player_list/%player_list menu spec causes function
  // player_list_load to be called passing %player_list as an arg.
  // whatever player_list_load returns is then passed into 
  // the page callback player_list_view_page
  $items['player_list/%player_list'] = array(
    'title' => 'View Player',
    'title callback' => 'player_list_view_title',
    'title arguments' => array(1),
    'page callback' => 'player_list_view_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'file' => 'player_list_view.inc',
    'type' => MENU_CALLBACK,
  );
  $items['player_list/%player_list/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['player_list/%player_list/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'player_list_edit_page',
    'page arguments' => array(1),
    'file' => 'player_list_update.inc',
    'access callback' => 'player_list_check_permission',
    'access arguments' => array(1,'3'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE|MENU_CONTEXT_INLINE,
  );

  // Delete player from list
  $items['player_list/%/delete/%/%'] = array(
    'title' => 'Delete Player From List',
    'page callback' => 'player_list_delete_from_list',
    'page arguments' => array(1,3,4),
    'access callback' => TRUE,
    'file' => 'player_list_delete.inc',
  );

  // Delete player from org
  $items['player_list/%/delorg/%'] = array(
    'title' => 'Delete Player From List',
    'page callback' => 'player_list_delete_from_org',
    'page arguments' => array(1,3),
    'access callback' => TRUE,
    'file' => 'player_list_delete.inc',
  );

  $items['player_list_list/add'] = array(
    'title' => 'Add Player List',
    'page callback' => 'player_list_list_add_to_org',
    'page arguments' => array(2),
    'access callback' => 'player_list_org_permission',
    'access arguments' => array(2),
    'file' => 'player_list_list_update.inc',
  );

  $items['player_list_list/%player_list_list'] = array(
    'title' => 'View Player List',
    'title callback' => 'player_list_list_view_title',
    'title arguments' => array(1),
    'page callback' => 'player_list_list_view_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'file' => 'player_list_list_view.inc',
    'type' => MENU_CALLBACK,
  );

  $items['player_list_list/%player_list_list/view'] = array(
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );

  $items['player_list_list/%player_list_list/admin'] = array(
    'title' => 'Admin',
    'page callback' => 'player_list_list_edit_page',
    'page arguments' => array(1),
    'file' => 'player_list_list_update.inc',
    'access callback' => 'player_list_check_permission',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE|MENU_CONTEXT_INLINE,
  );

  $items['player_list_list/%player_list_list/addp'] = array(
    'title' => 'Add New Player',
    'page callback' => 'player_list_list_addp_page',
    'page arguments' => array(1),
    'file' => 'player_list_update.inc',
    'access callback' => 'player_list_check_permission',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'context' => MENU_CONTEXT_PAGE|MENU_CONTEXT_INLINE,
  );

  // Delete player list
  $items['player_list_list/%player_list_list/delete'] = array(
    'title' => 'Delete Player List',
    'page callback' => 'player_list_delete_list_option',
    'page arguments' => array(1,3),
    'access callback' => TRUE,
    'file' => 'player_list_list_delete.inc',
  );

  $items['player_list/addto'] = array(
    'title' => 'Add player to list',
    'page callback' => 'player_list_add_to_list_page',
    'access callback' => TRUE,
    'file' => 'player_list_update.inc',
  );

  // Option to lookup user id for a player
  $items['player_list/%ctools_js/looku/%'] = array(
    'title' => 'Hello World',
    'page callback' => 'player_list_lookup_user',
    'page arguments' => array(1,3),
    'file' => 'player_list_lookup_user.inc',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  // When a player gets picked from the user lookup
  $items['player_list/%ctools_js/lookup/%player_list/%user'] = array(
      'title' => 'Hello World',
      'page callback' => 'player_list_select_user',
      'page arguments' => array(1, 3, 4),
      'access callback' => TRUE,
      'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * implementation of hook_entity_info().
 */
function player_list_entity_info() {
  $entities['player_list_player'] = array(
    'label' => t('Player'),
    'controller class' => 'PlayerListPlayerController',
    'views controller class' => 'EntityDefaultViewsController',
    'base table' => 'player_list_player',
    'uri callback' => 'player_list_player_uri',
    'fieldable' => TRUE,
    'module' => 'player_list',
    'entity keys' => array(
      'id' => 'pid',
      'label' => 'name',
    ),
    'admin ui' => array(
      'path' => 'admin/structure/player_list_player',
    ),
    'bundles' => array(
      'player_list_player'=> array(
        'label' => 'Player',
        'admin' => array(
          'path' => 'admin/structure/player_list_player/manage',
          'access arguments' => array('player list'),
        ),
      ),
    ),
    'staic cache' => TRUE,
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => FALSE,
      ),
    ),
  );

  $entities['player_list'] = array(
    'label' => t('Player List'),
    'controller class' => 'PlayerListController',
    'base table' => 'player_list',
    'uri callback' => 'player_list_uri',
    'fieldable' => TRUE,
    'module' => 'player_list',
    'entity keys' => array(
      'id' => 'lid',
      'label' => 'name',
    ),
    'admin ui' => array(
      'path' => 'admin/structure/player_list',
    ),
    'bundles' => array(
      'player_list'=> array(
        'label' => 'Player List',
        'admin' => array(
          'path' => 'admin/structure/player_list/manage',
          'access arguments' => array('player list'),
        ),
      ),
    ),
    'staic cache' => TRUE,
    'view modes' => array(
      'full' => array(
        'label' => t('Full content'),
        'custom settings' => FALSE,
      ),
    ),
  );

  return $entities;
}

/**
 * Implementation of hook_devel_entity_info().
 * So the devel_entity module can show entity information
 */
function player_list_devel_entity_info() {

  $info['player_list_player'] = array(
   'entity type' => 'player_list_player:player_list_player',
   'view path' => 'player_list_player/%player_list_player',
   'label' => 'name',
  );
  $info['player_list'] = array(
   'entity type' => 'player_list',
   'view path' => 'player_list/%player_list',
   'label' => 'name',
  );
  return $info;
}

function player_list_player_uri($player) {
  return array('path' => 'player_list_player/' . $player->pid,
  );
}

function player_list_player_save($player) {
  return entity_get_controller('player_list_player')->save($player);
}

function player_list_player_load($pid = NULL, $reset = FALSE) {
  $pids = (isset($pid) ? array($pid) : array());
  $conditions = array();
  $player = player_list_player_load_multiple($pids, $conditions, $reset);
  return $player ? reset($player) : FALSE;
}

function player_list_player_load_multiple($pids=array(), $conditions=array(), $reset=FALSE) {
  return entity_load('player_list_player', $pids, $conditions, $reset);
}

function player_list_player_delete($pid) {
  return player_list_player_delete_multiple(array($pid));
}

function player_list_player_delete_multiple($pids) {
  return entity_get_controller('player_list_player')->delete($pids);
}

function player_list_player_list_delete($lid) {
  return player_list_player_list_delete_multiple(array($lid));
}

function player_list_player_list_delete_multiple($lids) {
  return entity_get_controller('player_list_player_list')->delete($lids);
}

/**
*  List all players regardless of org.
*/
function player_list_org($org=0) {

  if($org != 0) {
    $content['top']['#markup'] = l('Add Player', 'player_list_player/add/' . $org);
  }

  $content['players']['#table'] = player_list_get_org_players($org);
  $content['players']['#theme'] = 'table';

  // Links on the bottom for subsequent pages
  $content['pager']['#markup'] = theme('pager');

  return $content;
}

function player_list_get_org_players($id, $type='org', $start=NULL, $linkText='player_list/', $delLink=FALSE, $nid=0) {
  $page = pager_find_page();
  $header = array();
  if( $delLink ) {
    $header[] = array('data' => 'Delete',               'field' => 'delete' );
  }
  $header[] = array('data' => 'Last name', 'field' => 'lastname', 'sort'=>'asc' );
  $header[] = array('data' => 'First name',      'field' => 'firstname' );
  $header[] = array('data' => 'Sex',             'field' => 'sex' );
  // Let other modules add header columns.
  $header = module_invoke_all('player_list_header', $header);

  $rows = array();
  $query = db_select('player_list_player', 'p');
  $query->fields('p', array('pid', 'dob', 'sex', 'firstname', 'lastname'));
  // join to get players in a list
  if($type == 'list' ) {
    $query->innerJoin('player_list_pids', 'lpp', 'lpp.pid = p.pid');
    $query->condition('lpp.lid', $id);
    $query->addField('lpp', 'pin', 'pin');
  } else {
    if($id != 0) {
      $query->condition('org', $id);
    }
  }
  // restrict to specified name
  if(isset($start)) {
    $query->condition('p.lastname', '%' . db_like($start) . '%', 'LIKE');
    // order by name
    $query->orderBy('p.lastname', 'ASC');
    $query->orderBy('p.firstname', 'ASC');
  } else {
    // Make table sortable (but not on the delete field! )
    if(!isset($_GET['order']) || $_GET['order'] != 'Delete') {
      $query = $query->extend('TableSort')->orderByHeader($header);
    }
  }
  $query = $query->extend('PagerDefault')->limit(50);
  // Label query so it can be altered by other modules
  $query->addTag('player_list_view');
//print out query
//dsm((string)$query);
  $result = $query->execute();
  $links = TRUE;
  $result_copy = array();
  foreach ( $result as $row) {
    $result_copy[]=$row;
    $pid = $row->pid;
    $firstname = $row->firstname;
    $lastname = $row->lastname;
    $delete = 'X';
    if($links) {
      if($nid == 0) {
        $lastname = l($row->lastname, $linkText . $pid );
      } else {
        $lastname = l($row->lastname, $linkText . $pid . "/$nid" );
      }
      if($type == 'org') {
        $delete = l('X', $linkText . "$pid/delorg/$id/$page");
      } else {
        $delete = l('X', $linkText . "$pid/delete/$id/$page");
      }
    }
    // Date of Birth only visible to logged in users
    $dob = player_list_get_dob($row->dob);
    $sex = $row->sex;
    if( $delLink ) {
      $newrow = array( $delete, $lastname, $firstname, $sex, $club );
    } else {
      $newrow = array( $lastname, $firstname, $sex, $club );
    }
    $rows[] = $newrow;
  }

  $table = array(
    'header' => $header,
    'data' => $rows,
  );

  $table = module_invoke_all('player_list_alter', $result_copy, $table);

  return $table;
}

function player_list_get_dob($date) {
  // Date of Birth only visible to logged in users
  if (user_is_logged_in()) {
    if(is_null($date)) {
      $dob = ' ';
    } else {
      $dob = date('Y-m-d',$date);
    }
  } else {
    $dob = '****';
  }
  return $dob;
}

function player_list_uri($list) {
  return array('path' => 'player_list/' . $list->lid,
  );
}

function player_list_save($list) {
  return entity_get_controller('player_list')->save($list);
}

function player_list_load($lid = NULL, $reset = FALSE) {
  $lids = (isset($lid) ? array($lid) : array());
  $conditions = array();
  $list = player_list_load_multiple($lids, $conditions, $reset);
  return $list ? reset($list) : FALSE;
}

function player_list_load_multiple($lids=array(), $conditions=array(), $reset=FALSE) {
  return entity_load('player_list', $lids, $conditions, $reset);
}

function player_lists_org($org) {

  $content['top']['#markup'] = l('Add Player List', 'player_list/add/' . $org);

  $content['players']['#table'] = player_list_get_org_lists($org);
  $content['players']['#theme'] = 'table';

  return $content;
}

// check if player is in a list
function player_list_in_list($pid, $lid) {
  $result = db_query("select count(*) from player_list_pids where lid=$lid and pid=$pid");
  $count = $result->fetchField();
  return $count!=0;
}

function player_list_get_org_lists($org) {

  $header = array(array('data' => 'List Name',         'field' => 'name' ),
                  array('data' => 'Number of Players', 'field' => 'nplayers' ),
                  array('data' => 'Excel', 'field' => 'excel' ),
  );

  $sql = "select lid, name, (select count(*) from player_list_pids where lid=l.lid) as nplayers from player_list l where l.org=$org order by name";
  $rows = array();
  $result = db_query($sql);

  $keys=array();
//print out query
  //dsm((string)$query);
  $links = TRUE;
  foreach ( $result as $row) {
    $lid = $row->lid;
    if(isset($row->name)) { 
      $name = $row->name;
    } else {
      $name = 'NULL';
    }
    $nplayers = $row->nplayers;
    // Add in any values for fields added by other modules
    $newrow = array( $name, $nplayers, $xl );
    foreach($keys as $key ) {
      $newrow[] = $row->$key;
    }
    $rows[] = $newrow;
  }

  $table = array(
    'header' => $header,
    'data' => $rows,
  );

  return $table;
}

function player_list_add_to_list($pid, $lid) {
  db_insert('player_list_pids')
    ->fields(array(
      'lid' => $lid,
      'pid' => $pid,
    ))
    ->execute();
}

function player_list_player_view_title($player) {
  $name = $player->firstname . ' ' . $player->lastname;
  // Seems to be needed despite returning a title
  drupal_set_title($name);
  return $name;
}

function player_list_view_title($list) {
  $name = 'Player List: '. $list->name;
  // Seems to be needed despite returning a title
  drupal_set_title($name);
  return $name;
}

function player_list_lists($org) {
//watchdog('player_list', "player_list_lists called with org $org");
  $rows = array();
  $sql = "select lid, name from player_list l where l.org=$org";
  $result = db_query($sql);
  foreach ( $result as $row) {
    $lid = $row->lid;
    $name = $row->name;
    $rows[$lid] = $name;
  }
  return $rows;
}

function player_list_user_text($uid) {
  if($uid == 0) {
    $text = "User Not Set";
  } else {
    $user = user_load($uid);
    $name = $user->field_name['und'][0]['value'];
    $text = $name . ' (' . $user->name . ')';
  }
  return $text;
}

/**
 *  Generate AJAX command to insert details looked up back into original form
 */
function player_list_select_user($js, $player, $user) {
  if (!$js) {
    // We don't support degrading this from js because we're not
    // using the server to remember the state of the table.
    return MENU_ACCESS_DENIED;
  }
  ctools_include('ajax');
  ctools_include('modal');

  $player->uid = $user->uid;
  player_list_save($player);

  $commands = array();
  $commands[] = ctools_modal_command_dismiss();
  $commands[] = array
  (
    // This command is defined in player_list.js
    // It puts the User selected into the original form
    'command' => 'insertPlayerUser',
    'uid' => $user->uid,
    'uname' => $user->name,
    'name' => $user->field_name['und'][0]['value'],
  );
  print ajax_render($commands);
  drupal_exit();
}

function player_list_org_permission($org) {
  $access = module_invoke_all('player_list_org_access', $org);
  return $access;
}
